server:
  port: 2222
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kafka?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: r@@T0000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true  # Uncomment this line if needed
    open-in-view: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: durgesh.y@drcsystems.com
    password: pcdzztscuegdnjxz
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Kafka configuration
  kafka:
    common:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      topic:
        name: order_topics
  #for producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #for consumers
    consumer:
      group-id: stock #group id set as per project or module Name
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"




logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate: INFO
    org.hibernate.cache: DEBUG
    org.hibernate.stat: DEBUG